<a href="https://colab.research.google.com/github/IqraAziz15/OpenRestaurantFYP/blob/master/model/My_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tens_flow
import tensorflow_datasets as tens_flow_ds
import tensorflow_hub as tens_hub

In [2]:
train_data, val_data, test_data = tens_flow_ds.load(name='imdb_reviews', split=('train[:60%]', 'train[60%:]', 'test'), as_supervised=True)

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteREFJ9K/imdb_reviews-train.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteREFJ9K/imdb_reviews-test.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteREFJ9K/imdb_reviews-unsupervised.tfrecord


Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [3]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))

In [4]:
train_examples_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [5]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

In [6]:
pretrained_model_for_word2vec = 'https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1'

In [7]:
hub_layer = tens_hub.KerasLayer(pretrained_model_for_word2vec, input_shape=[], dtype=tens_flow.string, trainable=True) 


In [8]:
hub_layer(train_examples_batch[:2])

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ]],
      dtype=float32)>

In [9]:
train_examples_batch[:2]

<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell a

In [10]:
model = tens_flow.keras.Sequential()
model.add(hub_layer)
model.add(tens_flow.keras.layers.Dense(16,activation='relu'))
model.add(tens_flow.keras.layers.Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense (Dense)                (None, 16)                336       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [12]:
model.fit(train_data.shuffle(10000).batch(1000), epochs=25, validation_data=val_data.batch(1000), verbose=1)

Epoch 1/25
30/30 [==============================] - 2s 81ms/step - loss: 1.4053 - accuracy: 0.4799 - val_loss: 0.7862 - val_accuracy: 0.4838
Epoch 2/25
30/30 [==============================] - 2s 80ms/step - loss: 0.7395 - accuracy: 0.5447 - val_loss: 0.6800 - val_accuracy: 0.5914
Epoch 3/25
30/30 [==============================] - 2s 79ms/step - loss: 0.6457 - accuracy: 0.6310 - val_loss: 0.6194 - val_accuracy: 0.6610
Epoch 4/25
30/30 [==============================] - 2s 82ms/step - loss: 0.5938 - accuracy: 0.6871 - val_loss: 0.5792 - val_accuracy: 0.6985
Epoch 5/25
30/30 [==============================] - 2s 81ms/step - loss: 0.5546 - accuracy: 0.7222 - val_loss: 0.5460 - val_accuracy: 0.7310
Epoch 6/25
30/30 [==============================] - 2s 80ms/step - loss: 0.5205 - accuracy: 0.7530 - val_loss: 0.5170 - val_accuracy: 0.7546
Epoch 7/25
30/30 [==============================] - 2s 79ms/step - loss: 0.4888 - accuracy: 0.7795 - val_loss: 0.4902 - val_accuracy: 0.7762
Epoch 8/25
30

In [13]:
model.predict(['''The most expensive in Islamabad with double taxation ,albeit tax is slashed half by regime.
The french toasts are cooked by putting custard inside and tea/paratha is too expensive.only one cup tea is served in combo deal of paratha.
Other stuff like steak and chinese dishes are too expensive;no fit for pakistan'''])

array([[0.06178254]], dtype=float32)

In [14]:
model.predict(['''he view on the drive here was beautiful and we managed to get good alfresco seats overlooking the hills. 
They had a good range of items on their menus, from Pakistani dishes to Western food. 
However, the food was less than satisfactory, the taste was just completely off.
 We are not usually complainers, but this was a complete rip-off as the prices were pretty high for this kind of substandard things on the plate which they called food.
Also, we had to witness a family of diners on the next table depositing their garbage into the hills, literally throwing tissues over the fence into the greenery below. 
The staff saw this, did nothing and I was holding down every muscle in my body from picking a fight with these inconsiderate adversaries of the environment.'''])

array([[0.01996678]], dtype=float32)

In [15]:
model.predict(['''Great service provided. Food quality good as always. Very busy but the service provided was still top notch. 
Contact free menu's using mobile and sanitisers available all across the restuarant. '''])

array([[0.99005246]], dtype=float32)

In [16]:
model.predict(['''Ordered Pakistani omelette and chicken sausage. The food was excellent and prepared perfectly.
It’s a great venue also. I was also surprised by the outstanding service and hygiene. Very good choice and a must go whilst in Islamabad.'''])

array([[0.9985187]], dtype=float32)

In [17]:
model.predict(['''Extremely disappointing service. Took us over an hour to get the food even when there were numerous tables open.
 Never got our coffees or chai even after reminding them three times. Had to even ask to get menus and then the same with water. 
 Only saving grace were the parathas.
Never returning!'''])

array([[0.04859418]], dtype=float32)